# enable mouse control 
set -g mouse on
# master key-bind for command
unbind C-b
set -g prefix C-s
set -g set-titles on

# reload configuration
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# don't do anything when a 'bell' rings
set -g visual-activity off
setw -g monitor-activity off
setw -g monitor-bell off
set -g bell-action none

# key-bind
# M - alt key
# C - ctrl key

# create session
bind C-c new-session

# window management
unbind ,
bind , command-prompt -p "Rename window:" "rename-window '%%'"

# windows
set -g status-justify 'left'
set -g status-left-length 80
set -g status-right-length 140
set -g status-right '[#(tmux ls -F "##S##{?session_attached,*,}" | tr "\\n" " " | sed "s/ $//" )]'
setw -g window-status-separator ''

# window navigation
unbind n
unbind p
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0
bind -r C-p previous-window
bind -r C-n next-window

# panes
# setw -g pane-border-status top
# set -g pane-scrollbars on
# set -g pane-scrollbars-position right
# set -g pane-active-border-style fg=#b294bb
# set -g pane-border-style fg=colour244

# create panes
bind j split-window -vb -c "#{pane_current_path}"
bind k split-window -v -c "#{pane_current_path}"
bind h split-window -hb -c "#{pane_current_path}"
bind l split-window -h -c "#{pane_current_path}"

# switch panes using Alt-hjkl
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-f resize-pane -Z

